version: '3.7'

services:
  database:
    image: postgres:11.5-alpine
    container_name: database-Postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: customPlates
    ports:
        - 5432:5432

  server:
    image: server-springboot
    build: 
      dockerfile: ./server/Dockerfile
    container_name: server-SpringBoot
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - 8080:8080
  
  client:
    image: client-react
    build:
      dockerfile: ./client/Dockerfile
    container_name: client-React
    depends_on:
      - server
    restart: unless-stopped
    ports:
      - 3000:3000