/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Resources of Plate
 */
export interface CollectionModelPlate {
    _embedded: models.EmbeddedCollectionPlate;

    /**
     * Link collection
     */
    _links: { [key: string]: models.Link; };

}
