/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface TemplateVariable {
    description?: string;

    name?: string;

    type?: TemplateVariable.TypeEnum;

}
export namespace TemplateVariable {
    export enum TypeEnum {
        CompositeParam = <any> 'COMPOSITE_PARAM',
        Fragment = <any> 'FRAGMENT',
        PathVariable = <any> 'PATH_VARIABLE',
        RequestParam = <any> 'REQUEST_PARAM',
        RequestParamContinued = <any> 'REQUEST_PARAM_CONTINUED',
        Segment = <any> 'SEGMENT'
    }
}
