/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Link {
    deprecation?: string;

    href?: string;

    hreflang?: string;

    media?: string;

    name?: string;

    profile?: string;

    rel?: object;

    title?: string;

    type?: string;

}
