/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ModelAndView {
    empty?: boolean;

    model?: object;

    modelMap?: { [key: string]: object; };

    reference?: boolean;

    status?: ModelAndView.StatusEnum;

    view?: models.View;

    viewName?: string;

}
export namespace ModelAndView {
    export enum StatusEnum {
        Accepted = <any> 'ACCEPTED',
        AlreadyReported = <any> 'ALREADY_REPORTED',
        BadGateway = <any> 'BAD_GATEWAY',
        BadRequest = <any> 'BAD_REQUEST',
        BandwidthLimitExceeded = <any> 'BANDWIDTH_LIMIT_EXCEEDED',
        Checkpoint = <any> 'CHECKPOINT',
        Conflict = <any> 'CONFLICT',
        Continue = <any> 'CONTINUE',
        Created = <any> 'CREATED',
        DestinationLocked = <any> 'DESTINATION_LOCKED',
        ExpectationFailed = <any> 'EXPECTATION_FAILED',
        FailedDependency = <any> 'FAILED_DEPENDENCY',
        Forbidden = <any> 'FORBIDDEN',
        Found = <any> 'FOUND',
        GatewayTimeout = <any> 'GATEWAY_TIMEOUT',
        Gone = <any> 'GONE',
        HttpVersionNotSupported = <any> 'HTTP_VERSION_NOT_SUPPORTED',
        ImUsed = <any> 'IM_USED',
        InsufficientSpaceOnResource = <any> 'INSUFFICIENT_SPACE_ON_RESOURCE',
        InsufficientStorage = <any> 'INSUFFICIENT_STORAGE',
        InternalServerError = <any> 'INTERNAL_SERVER_ERROR',
        IAmATeapot = <any> 'I_AM_A_TEAPOT',
        LengthRequired = <any> 'LENGTH_REQUIRED',
        Locked = <any> 'LOCKED',
        LoopDetected = <any> 'LOOP_DETECTED',
        MethodFailure = <any> 'METHOD_FAILURE',
        MethodNotAllowed = <any> 'METHOD_NOT_ALLOWED',
        MovedPermanently = <any> 'MOVED_PERMANENTLY',
        MovedTemporarily = <any> 'MOVED_TEMPORARILY',
        MultipleChoices = <any> 'MULTIPLE_CHOICES',
        MultiStatus = <any> 'MULTI_STATUS',
        NetworkAuthenticationRequired = <any> 'NETWORK_AUTHENTICATION_REQUIRED',
        NonAuthoritativeInformation = <any> 'NON_AUTHORITATIVE_INFORMATION',
        NotAcceptable = <any> 'NOT_ACCEPTABLE',
        NotExtended = <any> 'NOT_EXTENDED',
        NotFound = <any> 'NOT_FOUND',
        NotImplemented = <any> 'NOT_IMPLEMENTED',
        NotModified = <any> 'NOT_MODIFIED',
        NoContent = <any> 'NO_CONTENT',
        Ok = <any> 'OK',
        PartialContent = <any> 'PARTIAL_CONTENT',
        PayloadTooLarge = <any> 'PAYLOAD_TOO_LARGE',
        PaymentRequired = <any> 'PAYMENT_REQUIRED',
        PermanentRedirect = <any> 'PERMANENT_REDIRECT',
        PreconditionFailed = <any> 'PRECONDITION_FAILED',
        PreconditionRequired = <any> 'PRECONDITION_REQUIRED',
        Processing = <any> 'PROCESSING',
        ProxyAuthenticationRequired = <any> 'PROXY_AUTHENTICATION_REQUIRED',
        RequestedRangeNotSatisfiable = <any> 'REQUESTED_RANGE_NOT_SATISFIABLE',
        RequestEntityTooLarge = <any> 'REQUEST_ENTITY_TOO_LARGE',
        RequestHeaderFieldsTooLarge = <any> 'REQUEST_HEADER_FIELDS_TOO_LARGE',
        RequestTimeout = <any> 'REQUEST_TIMEOUT',
        RequestUriTooLong = <any> 'REQUEST_URI_TOO_LONG',
        ResetContent = <any> 'RESET_CONTENT',
        SeeOther = <any> 'SEE_OTHER',
        ServiceUnavailable = <any> 'SERVICE_UNAVAILABLE',
        SwitchingProtocols = <any> 'SWITCHING_PROTOCOLS',
        TemporaryRedirect = <any> 'TEMPORARY_REDIRECT',
        TooEarly = <any> 'TOO_EARLY',
        TooManyRequests = <any> 'TOO_MANY_REQUESTS',
        Unauthorized = <any> 'UNAUTHORIZED',
        UnavailableForLegalReasons = <any> 'UNAVAILABLE_FOR_LEGAL_REASONS',
        UnprocessableEntity = <any> 'UNPROCESSABLE_ENTITY',
        UnsupportedMediaType = <any> 'UNSUPPORTED_MEDIA_TYPE',
        UpgradeRequired = <any> 'UPGRADE_REQUIRED',
        UriTooLong = <any> 'URI_TOO_LONG',
        UseProxy = <any> 'USE_PROXY',
        VariantAlsoNegotiates = <any> 'VARIANT_ALSO_NEGOTIATES'
    }
}
